### ISSUE TITLE
Vertaisarvionti

### ISSUE THREAD

**Issue by 000hcl** [VoxBorealis/To-Do-List-Web-Application#1]
Log in sivulla voi painaa Log Out, vaikka ei ole vielä kirjautunut sisään. 

Completed sivulla 'View Completed Tasks'-nappi voisi olla jotain muuta, esim. takaisin-nappi.

Ohjelma  on mukava käyttää ja näyttää toimivan hyvin tässä vaiheessa. 

Koodi on selkeä ja hienosti jaettu eri tiedostoihin.

**Comment by VoxBorealis** [comment]
Kiitos palautteesta! Otan nämä asiat huomioon.
